[source]
type = "N2N"
address = "relays-new.cardano-mainnet.iohk.io:3001"

[[reducers]]
type = "AddressByAsset"
key_prefix = "AddressByAdaHandle"
policy_id_hex = "f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a"
convert_to_ascii = true

[storage]
type = "Redis"
connection_params = "redis://redis:6379"

[chain]
type = "Mainnet"

[intersect]
type = "Point"
value = [
    76066702,
    "9e1a6284f0ff3bd59cabb2eac9feef4acefe8cd10c5b63825dfdea79f65bfcea",
]
