[source]
type = "N2N"
address = "preprod-node.world.dev.cardano.org:30000"

[[reducers]]
type = "AddressByAdaHandle"
key_prefix = "AddressByAdaHandle"
policy_id_hex = "f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a"

[storage]
type = "Redis"
connection_params = "redis://127.0.0.1:6379"

[chain]
type = "PreProd"

[intersect]
type = "Point"
value = [
    8261225,
    "103ff3cfec6e388db803fc10dbdecb3026b4a51382008d01ff3f9121be6fa6e4",
]
