[source]
type = "N2N"
address = "relays-new.cardano-mainnet.iohk.io:3001"

[[reducers]]
type = "UtxoByNft"
key_prefix = "c2"

[storage]
type = "Redis"
connection_params = "redis://127.0.0.1:6379"

[intersect]
type = "Point"
value = [
    75763928,
    "081ede3bfac7d736625db5d4ad6c8024b46c8630329bf9155930bc3f2f511f5c",
]

[chain]
type = "Mainnet"

[policy]
missing_data = "Skip"
