[source]
type = "N2N"
address = "preprod-node.world.dev.cardano.org:30000"

[chain]
type = "PreProd"

[enrich]
type = "Sled"
db_path = "./data/sled_db"

[[reducers]]
type = "LiquidityByTokenPair"
# optional redis key prefix
pool_prefix = "pool" 
# optional redis member prefix
dex_prefix = "min" 
# mandatory native asset policy id that marks valid liquidity pools
pool_currency_symbol = "0be55d262b29f564998ff81efe21bdc0022621c12f15af08d0f2ddb1"
# serialization format for redis members, by default false resulting in ':' separated values
# json_value = true

[[reducers]]
type = "LiquidityByTokenPair"
# optional redis key prefix
pool_prefix = "pool" 
# optional redis member prefix
dex_prefix = "wrt" 
# mandatory native asset policy id that marks valid liquidity pools
pool_currency_symbol = "fbaec8dd4d4405a4a42aec11ce5a0160c01e488f3918b082ccbab705"
# serialization format for redis members, by default false resulting in ':' separated values
json_value = true

[policy]
missing_data = "Skip"

[storage]
type = "Redis"
connection_params = "redis://redis:6379"

[intersect]
type = "Tip" # or "Origin" to get all available liquidity pools
