[source]
type = "N2N"
address = "relays-new.cardano-mainnet.iohk.io:3001"

[[reducers]]
type = "UtxoByAddress"
key_prefix = "c1"

[[reducers]]
type = "PointByTx"
key_prefix = "c2"

[storage]
type = "Redis"
connection_params = "redis://redis:6379"

[intersect]
type = "Point"
value = [57867490, "c491c5006192de2c55a95fb3544f60b96bd1665accaf2dfa2ab12fc7191f016b"]

[chain]
type = "Mainnet"
