[source]
type = "N2N"
address = "relays-new.cardano-mainnet.iohk.io:3001"

[enrich]
type = "Sled"
db_path = "./data/sled_db"

[[reducers]]
type = "FullUtxosByAddress"
filter = ["addr1z8snz7c4974vzdpxu65ruphl3zjdvtxw8strf2c2tmqnxz2j2c79gy9l76sdg0xwhd7r0c0kna0tycz4y5s6mlenh8pq0xmsha"]
# address_as_key = false

[storage]
type = "Redis"
connection_params = "redis://redis:6379"

[intersect]
type = "Tip"

[chain]
type = "Mainnet"

[policy]
missing_data = "Skip"
