# [source]
# type = "N2N"
# address = "relays-new.cardano-mainnet.iohk.io:3001" 
# address = ["Tcp", "preprod-node.world.dev.cardano.org:30000"] # address = ["Tcp", "preprod-node.world.dev.cardano.org:30000"]

[source]
type = "N2N"
address = "preprod-node.world.dev.cardano.org:30000"
magic = "preprod"

[[reducers]]
type = "UtxoByAddress"
key_prefix = "minswap.order"
# Order Contract address
# filter = ["addr1wxn9efv2f6w82hagxqtn62ju4m293tqvw0uhmdl64ch8uwc0h43gt"]

[storage]
type = "Redis"
connection_params = "redis://redis:6379"

[intersect]
type = "Origin"

[chain]
type = "Mainnet"

[policy]
missing_data = "Skip"
